### ISSUE TITLE
Replace Settings with "some" configuration

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#115]
The `Settings` interface is pretty much a configuration element. As soon as it became clear, if JSR 382 remains in its current form or may also turn into a Jakarta EE spec (like it's intended for JNoSQL) wouldn't it be possible to replace it with a `Config` element from that spec?

IMO MicroProfile config is not the right place to use, because it is not an official spec or standard, it acts primarily as a "sandbox".

**Comment by otaviojava** [comment]
Werner, we started that discussion in the JSR Config.
The project stopped, furthermore, on the discussion the scope isn't to SE.
We have integrations to other specifications, however, JSR Config neither is ready and the scope to Java SE.

**Comment by keilw** [comment]
I am not talking about the JSR, @davidblevins mentioned a possible factor into Jakarta EE ("jakarta.config" in the same slides he also proposed to add JNoSQL) of either JSR 381 or MicroProfile Config (frankly I care less which one, as long as it's available as a spec like all the othrs, MP Config makes a much more active impression which is why the JSR suffers from that ;-/)

**Comment by otaviojava** [comment]
We had that discussion yesterday at the Jakarta Q&A. 
But that still uncertain when.

**Comment by keilw** [comment]
The JSR 382 EG leans towards a move to Jakarta EE. And at least on the implementation side projects that support either JSR 382, MicroProfile Config or both could be used. I can't say, if Spec/API dependencies exist, those may need an official config specification, while implementations especially those at Eclipse should have no issue using e.g. MicroProfile for now.

**Comment by keilw** [comment]
While the dilemma of a MicroProfile (Config) dependency that is outdated exists I think this one as such can be closed.
