### ISSUE TITLE
Support For Reactive Streams or Flow Api of Java 9

### ISSUE THREAD

**Issue by ankurpathak** [eclipse/jnosql#116]
Since This Project is New and will be soon part of Jakarata EE.
We should also add API which Supports Reactive Streams
or Flow Api of Java 9. We already have reactive drivers available
for many databases like:
Key Value: Redis
Documnet: MongoDB
We should have Reactive Support atleast for Databases which
have Reactive Driver Available.

**Comment by keilw** [comment]
There is a possible overlap with MicroProfile: https://groups.google.com/forum/?hl=en#!topic/microprofile/Em24P1UCcPE

**Comment by otaviojava** [comment]
I live this idea

**Comment by ankurpathak** [comment]
> I live this idea

@otaviojava Do we have any plan for Reactive Support?

**Comment by otaviojava** [comment]
Yes, we do.
We're waiting to more stability at the Eclipse Reactive.

**Comment by hantsy** [comment]
I think this is related to #232

**Comment by otaviojava** [comment]
Thank you @hantsy

**Comment by otaviojava** [comment]
We'll close this issue for awhile.

I'll focus on supporting what we have on Jakarta NoSQL and Jakarta Data spec.
