### ISSUE TITLE
Creates a pagination resource at the Repository interface

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#123]
As feedback from community, this issue is to study the possibility to we have a repository with pagination support.

## References:

* https://www.baeldung.com/spring-data-jpa-pagination-sorting
* https://www.logicbig.com/tutorials/spring-framework/spring-data/pagination.html
* https://docs.spring.io/spring-data/rest/docs/2.0.0.M1/reference/html/paging-chapter.html

**Comment by adam-waldenberg** [comment]
@otaviojava Another solution would be to just support, `skip()` and `limit()' in the repository interfaces. This would allow us to easily support pagination in the repository methods we define. Being able to write something like;

```@Dependent
public interface EmailRepository extends Repository<Email, String> {
	List<Email> findByAccountSkipLimit(ObjectId objectId, long skip, long limit);
}
```

... would have been very useful.

**Comment by adam-waldenberg** [comment]
I guess we can close this now that #160 adds a working solution?

**Comment by otaviojava** [comment]
Yes.
Thank you @adam-waldenberg
