### ISSUE TITLE
Define alias configuration in communication

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#166]
Currently, we have  different configurations to each NoSQL database provider, E..g.:

* cassandra-host
* mongodb-server-host

The context here is to define default alias configuration that will also work with both, e.g:

* jakarta.nosql.host

Also, define commons ones, such as:

* jakarta.nosql.user
* jakarta.nosql.password
* jakarta.nosql.query

**Comment by otaviojava** [comment]
https://github.com/eclipse/jnosql-diana-driver/issues/129

**Comment by odrotbohm** [comment]
What if someone uses multiple stores in their application?

**Comment by otaviojava** [comment]
The settings database have support to file such as XML, JSON, and YAML.
A unit of a settings database is configuration, and each Configuration has its container. Therefore there are no impacts, .e.g.:

```json
[
   {
      "name":"document",
      "settings":{
         "jakarta.nosql.user":"user",
         "jakarta.nosql.password":"password"
      }
   },
   {
      "name":"document-2",
      "settings":{
         "jakarta.nosql.user":"user-2",
         "jakarta.nosql.password":"password-2"
      }
   }
]
```
Does it make sense?
What do you think?

**Comment by keilw** [comment]
The password should never be in plain text, what is the solution here? Or do we have to rely on multiple vendors doing their own thing on encrypting it? 
In either way the use of plain text passwords except for quick and dirty demos should be discouraged.

We'd still hope, that a configuration standard usable to a (hopeful) Jakarta EE spec arises, but at least those who also deal with either JSR 382, MicroProfile or both know, this is not clear yet and the project undecided whether to go "Full Jakarta EE" now or try to finalize the JSR first (only to be likely forced into a migration anyway when entering the Jakarta EE platform ;-p)

**Comment by otaviojava** [comment]
I agree, that why I started the discussion about it here:
https://github.com/eclipse/jnosql/issues/162
