### ISSUE TITLE
Find a light library to YAML reader.

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#172]
The jackson is a nice library, however, it brings several other dependencies. That would be amazing if we can use a light library to the same proposal.

**Comment by otaviojava** [comment]
E.g: https://www.baeldung.com/java-snake-yaml

**Comment by keilw** [comment]
It has to be Eclipse compliant, e.g. in Orbit already. What aspects of YAML are needed? Just config, then it might be (for implementing modules) an option to use e.g. MicroProfile Config or similar which hopefully soon can be replaced by a Jakarta EE Config Spec.

**Comment by otaviojava** [comment]
Yes, just for config
