### ISSUE TITLE
Isn't this an implementation of the jakarta.nosql spec?

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#182]
I saw, the POM defines a parent
```
<parent>
        <groupId>jakarta.nosql</groupId>
        <artifactId>jakarta-nosql-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

```
However, if it is an implementation of the Jakarta NoSQL spec/API, wouldn't it be better or correct to have its own parent here?

**Comment by otaviojava** [comment]
It does:
https://github.com/eclipse/jnosql/blob/master/pom.xml

It extends from the Jakarta NoSQL do reduce the duplicated code. But JNoSQL has own parent.

**Comment by keilw** [comment]
@waynebeaton Sorry to bother, but curious, are implementations supposed to use the Spec as a "Parent POM" like JNoSQL does here, or more like e.g. Krazo: https://github.com/eclipse-ee4j/krazo/blob/master/pom.xml which defines a Parent POM in its repo sitting above multiple modules. If JNoSQL ends up with more than one repository, it may need a Parent, but can that be the Spec?

**Comment by keilw** [comment]
Aside from the question of a parent POM, @waynebeaton wouldn't it make sense to also have this repository (and all other "jnosql-*" ones that are not archived) in  https://github.com/eclipse-ee4j/ ?

All implementation projects of Jakarta specs are there and even the "krazo" project that implements the MVC JSR which is not in Jakarta EE also got located under EE4J.

**Comment by waynebeaton** [comment]
The specification project needs to be independent of any particular implementation. Other than that, I don't care.

We discussed the organization of projects in a different thread. The short version is: maybe but not necessarily. After we reorg EE4J (post Jakarta EE 8 release), we can have that discussion.

**Comment by keilw** [comment]
That's fine, not sure, if we could use the 
```
  <parent>
        <groupId>org.eclipse.ee4j</groupId>
        <artifactId>project</artifactId>
        <version>1.0.1</version>
    </parent>
```
like e.g. Tyrus or other implementations do, regardless of the TLD?
Otherwise I would rather use the old eclipse-parent because the Jakarta parent should not be in this POM, only as dependencies or a BOM if we had it.
