### ISSUE TITLE
Are we allowed to keep the org.jnosql package here?

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#183]
While the Spec and standardized API are defined in the new `jakarta.nosql` project, why are there so many org.jnosql packages in this repository and others? Shouldn't it be `org.eclipse.jnosql` instead similar to e.g. MicroProfile?
It also has an external ".io" Website, but the package structure uses org.eclipse, which is common to almost every Eclipse project.

**Comment by otaviojava** [comment]
Eclipse holds the JNoSQL.org domain, I believe there is no issue on that.

**Comment by keilw** [comment]
Again @waynebeaton as you are also mentor, is it OK or are projects encouraged to use `org.eclipse`? I know MicroProfile had a discussion about that, vert.x is among the few using its own "io" package name, so what is the preference of Eclipse Foundation if any? Eclipse Foundation also registered the `microprofile.io` domain, but that does not mean MicroProfile APIs or features are supposed to use that.

**Comment by keilw** [comment]
@waynebeaton @otaviojava Any thoughts on that? I know, at least Glassfish still keeps its `org.glassfish` namespace and it may take several releases of Jakarta EE before  that could change if ever, but Glassfish has been mature and stable for many years, while JnoSQL until now could probably just be considered an Alpha release with no significant user base that would be forced to migrate if it changed.

**Comment by keilw** [comment]
I spoke to the project lead of Jetty and @ivargrimstad at JCrete, they both suggested `org.eclipse.nosql` could be the better option, but should Eclipse Foundation really have taken ownership of the `org.jnosql` domain, then maybe both are possible. @waynebeaton Is that the case?

**Comment by waynebeaton** [comment]
As a Jakarta EE Specification project, I believe that the best option is `jakarta.nosql` for APIs. Implementation would be under `org.eclipse.*`, but AFAIK Jakarta NoSQL does not provide any implementation. Anything else is considered exceptional. Regardless of whether or not the Eclipse Foundation owns the domain.

**Comment by keilw** [comment]
That's correct, e.g. https://github.com/eclipse/jnosql/blob/master/diana/diana-core/src/main/java/org/jnosql/diana/DefaultSort.java implements https://github.com/eclipse-ee4j/nosql/blob/master/communication/communication-core/src/main/java/jakarta/nosql/Sort.java. So this project (JNoSQL) is an implementation of Jakarta NoSQL. We shall refactor it with the next releases. Thanks for the clarification.
