### ISSUE TITLE
Use a different parent POM

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#195]
#182 helped answer questions about the independence of implementation projects from Jakarta NoSQL. There should be no Parent POM of the spec used in an implementation project like this one. At most a BOM (still TBD for NoSQL) could be a dependency, but the Parent POM should be either Eclipse general parent or one for EE4J.

- [ ] Analyze what properties or other aspects of https://github.com/eclipse-ee4j/nosql/blob/master/pom.xml are used here
- [ ] Change the Parent POM to either Eclipse Parent or something specific to EE4J

**Comment by otaviojava** [comment]
@dearrudam will your PR fix this one?

**Comment by dearrudam** [comment]
@otaviojava yeah! I'm working on it!!
