### ISSUE TITLE
Point to CI server

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#199]
A Jenkins CI instance was created as per #129 but there is no link or status badge here in the Readme.

**Comment by almeidaah** [comment]
I will open a PR to this. 
I couldn't get the badge(from CI config) since I don't have access. [Here] is how to get the badges: (https://circleci.com/docs/2.0/status-badges/)

**Comment by almeidaah** [comment]
@keilw can we close?

**Comment by keilw** [comment]
No, there's at least a typo in the readme or a relic from a previous tool: "Circle CI Integration" makes no sense for a URL that actually points to the Eclipse Jenkins farm. @almeidaah could you provide another PR that fixes that?

**Comment by keilw** [comment]
The "JNoSQL" is unnecessary given the other points, but either "Jenkins" or "CI Server" sounds fine, the latter would be more neutral ;-)
