### ISSUE TITLE
Change groupId

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#205]
Along the planned change of the package (#183) the Maven groupId should also use `org.eclipse.jnosql`.

**Comment by keilw** [comment]
@waynebeaton Is there anything we'd have to request for that with Sonatype, or does any groupId under `org.eclipse` work for Eclipse projects anyway?

**Comment by otaviojava** [comment]
I guess we can request it without a problem.

@keilw 
What is the the name convention?

## Communicatoin 
* org.eclipse.nosql.diana.*
E.g.:
* org.eclipse.nosql.diana.keyvalue
* org.eclipse.nosql.diana.column
* org.eclipse.nosql.diana.document


## Mapping
* org.eclipse.nosql.artemis.*

E.g.:
* org.eclipse.nosql.artemis.keyvalue
* org.eclipse.nosql.artemis.column
* org.eclipse.nosql.artemis.document
* org.eclipse.nosql.artemis.graph

**Comment by waynebeaton** [comment]
For most Eclipse projects, the standard is "org.eclipse.<shortname>", so in the case of Eclipse JNoSQL, it should be "org.eclipse.jnosql".

For specification projects run under the supervision of the Jakarta EE working group, the standard is to use "jakarta.<shortname>", so for Jakarta NoSQL, it should be "jakarta.nosql".

**Comment by otaviojava** [comment]
@keilw 
https://github.com/eclipse/jnosql/pull/206

**Comment by otaviojava** [comment]
Request the group.id:
https://issues.sonatype.org/browse/OSSRH-51415

**Comment by otaviojava** [comment]
I also created a ticket to do it by Jenkins.

**Comment by otaviojava** [comment]
Hey everybody, yesterday, I created PRs to adjustment to the new Group id.
Right now, we're moving to the new JNoSQL infra.

**Comment by keilw** [comment]
Will those two PRs work without creating a conflict?

**Comment by otaviojava** [comment]
Now it is working :).
I need to create the publisher jobs, I'll do it after the Jarkarta One sessions.

**Comment by otaviojava** [comment]
Finally, we have all set up that includes the Jenkins instances:

* Eclipse JNoSQL: https://ci-staging.eclipse.org/jnosql/
* Jakarta NoSQL: https://ci.eclipse.org/nosql/
