### ISSUE TITLE
Support @Transactional 

### ISSUE THREAD

**Issue by hantsy** [eclipse/jnosql#233]
In Spring Data, some NoSQL databases got transaction support, such as Mongo(in cluster), Redis. 

I think JNoSQL should consider the CDI compatible `@Transactional` APIs(transaction could be a standard alone APIs in the future Jakarta EE ), and add it in the NoSQL which supports transactions.

**Comment by otaviojava** [comment]
Hey @hantsy good point. we can talk about it. For sure it might be a great annotation

**Comment by hantsy** [comment]
Currently, the [transaction APIs](https://jakarta.ee/specifications/transactions/1.3/) is too dependent on JakaraEE containers( the application servers ) and esp, used with the existing EJB, JTA, JMS, etc.  I am not sure if it is possible to ported into JNoSQL, and as I know the @Transactional is supported in Oracle Helidon and Redhat Quarkus.

And NoSQL will support SE and EE, like the JPA?

**Comment by otaviojava** [comment]
Usually, the NoSQL database does not support a precious transaction resource. When they have it such as MongoDB, they don't recommend it in favor of denormalization.
That is a good topic to study and analyze; however, we can create an extension and move to the API when we got more confidence.
Reference: https://docs.mongodb.com/manual/core/transactions/

**Comment by otaviojava** [comment]
We'll close this one for inactivity.

**Comment by hantsy** [comment]
Mongo, Redis, Neo4j all have transaction concept, and Spring support them with Spring Transaction.
