### ISSUE TITLE
Support to PageCursor

### ISSUE THREAD

**Issue by FlavioSantoro92** [eclipse/jnosql#243]
Hi.
Some other nosql database uses a cursor instead of an offset for the pagination.
Could you add in the interface of the driver a method could accept a generic Object in order to achieve this in new drivers?

**Comment by otaviojava** [comment]
Hello Flavio, how are you?
By default, the result returns a `Stream` it is because it is lazy as a cursor. If you're using MongoDB the `Stream` fits you once both are lazy.
