### ISSUE TITLE
Remove or replace the logo

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#250]
Even for an Eclipse project, using the Duke mascot seems inappropriate and should be changed.
Either we replace the logo with something else or remove it for the time being.

We have to remove/replace the logo in multiple places
- [ ] JNoSql.org site
- [x] This repo and README
- [x] Eclipse.org Wiki

**Comment by otaviojava** [comment]
As far I know, there is no logo in the Jakarta NoSQL, only to JNoSQL.
But I'll review the documentation again.

**Comment by keilw** [comment]
The Duke mascot is not allowed for Eclipse projects, as long as "JNOSQL" stands for the compatible implementatoin that means we also have to replace it there.

**Comment by otaviojava** [comment]
Duke is a BSB license.
https://www.oracle.com/java/duke.html
The MVC, Bean Validation also have been using it.

**Comment by keilw** [comment]
While they were under the JCP, I don't see https://github.com/eclipse-ee4j/krazo use it, hence this one should not use it either. It's Eclipse branding practices. While a JUG may be fine to use Duke, an Eclipse project shouldn't.

**Comment by keilw** [comment]
@otaviojava See https://github.com/eclipse-ee4j/beanvalidation-spec/issues/264#issuecomment-720637909 that means, we must also change or remove the Duke-based logo here. It is fine to use Duke images in the documentation where it helps, but the logo itself must be "Duke-less".

**Comment by keilw** [comment]
We have to remove/replace the logo in multiple places
- [ ] JNoSql.org site
- [ ] This repo and README
- [ ] Eclipse.org Wiki

**Comment by otaviojava** [comment]
@keilw I'll remove the logo from the readme.
