### ISSUE TITLE
Nightly build repository

### ISSUE THREAD

**Issue by amoscatelli** [eclipse/jnosql#252]
Hi there !
Is there a nightly build repository ?
I looked for an eclipse foundation maven but I didn't find anywhing

I would like to fetch artifacts without pushing them myself on a local maven repository ...

Thank you

**Comment by keilw** [comment]
There should be a Jenkins instance.

**Comment by amoscatelli** [comment]
@keilw 
You mean this ?
https://ci.eclipse.org/jnosql/

Yea, but I need an artifact repository. Also I can't start/run any of those jobs.

For example
https://maven.scijava.org/content/repositories/public/org/eclipse/jnosql/communication/dynamodb-driver/1.0.0-SNAPSHOT/

Here I can find 
dynamodb-driver-1.0.0-20210107.103215-2.jar

This is from 15 days ago, juse like the related Jenkins job last execution : 

![image](https://user-images.githubusercontent.com/16684470/105528736-a32f8a00-5ce5-11eb-919b-e81deaf3591d.png)

Where do these jobs deploy the artifacts to ?

**Comment by keilw** [comment]
I don't know, they should do it to a SNAPSHOT repo, either on Sonatype or JFrog. Only milestones are supposed to be deployed to the official repos.

**Comment by amoscatelli** [comment]
Found in the job logs!
https://oss.sonatype.org/content/repositories/snapshots/

@otaviojava may I ask you to run the jenkins job to release a new snapshot ?
Thank you

**Comment by otaviojava** [comment]
@amoscatelli there is a script to run it monthly.

**Comment by otaviojava** [comment]
Please, let me know if you need something.
