### ISSUE TITLE
Could Apache TinkerPop mention JNoSQL?

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#295]
This project page obviously mentions Apache TinkerPop for Graph-DB support, so could we also ask the TinkerPop to mention JNoSQL under "Java > Third-Party Libraries and Tools" of its [community](https://tinkerpop.apache.org/community.html) page?

**Comment by otaviojava** [comment]
That is good question, I'll request it.

**Comment by otaviojava** [comment]
Done: https://lists.apache.org/list.html?dev@tinkerpop.apache.org

**Comment by otaviojava** [comment]
Done
![Screenshot from 2023-01-11 10-56-21](https://user-images.githubusercontent.com/863011/211824437-4b0ff756-4852-475e-8870-5a800ccc7558.png)
