### ISSUE TITLE
Fix SNAPSHOT in POM

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql#308]
The SNAPSHOT version in all POMs should not be `1.0.0-b6-SNAPSHOT` but `1.0.0-SNAPSHOT`.

**Comment by dearrudam** [comment]
@keilw, as the `jakarta.nosql:jakarta-nosql-parent:1.0.0-SNAPSHOT` doesn't cover the Jakarta EE dependency bigbang change, do you think that it's a good to define a own version for this project? I mean, do you think that it's a good idea adding the version tag into the POM of the `jnosql-parent` project like this:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
        <parent>
		<groupId>jakarta.nosql</groupId>
		<artifactId>jakarta-nosql-parent</artifactId>
		<version>1.0.0-b6-SNAPSHOT</version>
	</parent>
	<groupId>org.eclipse.jnosql</groupId>
	<artifactId>jnosql-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
        <!-- xml snippet -->
</project>
```
And cascade this version to its children modules?

**Comment by keilw** [comment]
@dearrudam The snapshot should be for the actual first real release 1.0.0, regardless of how many "Beta" or similar milestone releases are published. Not sure, what you mean the parent does not cover something. It means **THIS** repository, not some snapshot of dependencies, although the Jakarta NoSQL.

The whole 
```
<parent>
		<groupId>jakarta.nosql</groupId>
		<artifactId>jakarta-nosql-parent</artifactId>
		<version>1.0.0-b6-SNAPSHOT</version>
	</parent>
```
Is also very wrong btw (will create another issue) as the implementation project should be independent from the API.
This has to be done differently via `dependencyManagement` or maybe some kind of POM.

**Comment by otaviojava** [comment]
Yeap, good point, we need to remove this dependency and split from the spec.

Thank you @keilw
