### ISSUE TITLE
nosql.version>1.0.0-b6-SNAPSHOT in jnosl.pom

### ISSUE THREAD

**Issue by redmitry** [eclipse/jnosql#331]
Hello,
Just wondering: [jnosql.pom](https://github.com/eclipse/jnosql/blob/e8d952207d5e41465e473da63c3ab648f1c65538/pom.xml#L67)

Shouldn't it be replaced with "1.0.0-SNAPSHOT" now?

D.

P.S.
I also found no 1.0.0-SNAPSHOT drivers  :-(
https://mvnrepository.com/artifact/org.eclipse.jnosql.communication/jnosql-mongodb-driver

**Comment by keilw** [comment]
I thought there was a PR for that, or did it not work everywhere?

**Comment by redmitry** [comment]
I think this variable has no use anywhere.
Regarding the drivers, was my fault, as I didn't include 
https://jakarta.oss.sonatype.org/content/repositories/snapshots/ snapshot repo.
