### ISSUE TITLE
Create default issues template at Eclipse JNoSQL

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#338]
To make more accessible contributions to the Eclipse JNoSQL project, we could create some issues templates:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

We could use Jakarta Data as sample:

https://github.com/jakartaee/data/tree/main/.github/ISSUE_TEMPLATE

**Comment by viniciusbrg** [comment]
Hey @otaviojava, isn't this issue covered by #342 ?

**Comment by otaviojava** [comment]
Ops, you're right.
Closing this one.
