### ISSUE TITLE
Increase the experience to open issues inside the Eclipse JNoSQL

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#342]
As a user, I want to have a couple of options to create an issue:

* Proposal a new database
* Propose to update the database
* Proposal of a new feature
* Identify a bug

## Proposal

The goal is to have more than four templates to cover those scenarios.

**Comment by viniciusbrg** [comment]
Hello, the project already has two templates: one for bug reports and another for feature requests.

Do you think we still need to work on them?

Another interesting thing is [github issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), which is currently in beta.

Here is a project using it: https://github.com/eclipse/jkube/issues/new/choose

**Comment by viniciusbrg** [comment]
Alright @otaviojava I'll let you know if I have any questions about this
