### ISSUE TITLE
Add CI support for Java 20

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#352]
As discussed in today's meeting, Mar 29, we need to support the latest LST, Java 17, and be ready for the next LST version, Java 21.

This issue will create a GitHub Action, CI, to run the source code against Java 20; this won't impact the code behavior.
It is an excellent issue to the first contribution.

To-Do:

- [ ]  Create a GitHub Action that runs the Jakarta NoSQL source code against Java 20
- [ ]  Test the Action and ensure it correctly detects any compatibility issues
- [x]  Update the README to document the new CI support for Java 20
- [x] Reproduce the something on [communication](https://github.com/eclipse/jnosql-communication-driver) and [extension](https://github.com/eclipse/jnosql-mapping-extension) repositories

**Comment by viniciusbrg** [comment]
Hello @otaviojava 
Can I work on this issue?

**Comment by otaviojava** [comment]
Sure @viniciusbrg

**Comment by viniciusbrg** [comment]
@otaviojava just opened the PR's in the extensions and databases repo

**Comment by otaviojava** [comment]
Thank you, @viniciusbrg both merged.
