### ISSUE TITLE
Merge jnosql-communication-driver and jnosql-mapping-extension repositories into a single module[Task]

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#355]
The task for the: https://github.com/eclipse/jnosql/issues/353

## Structure

- [x] Rename the project from `jnosql-communication-driver` to `jnosql-databases`
- [x] Rename the project from `jnosql-mapping-extension` to `jnosql-extensions`
- [x] Update Parent-pom to use `org.eclipse.jnosql.databases` as group ID
- [x] Create and define tags to test that needs a database and disable it by default.

## Merge project

This one needs to merge communication and mapping into a single module.

* We need to be sure that we won't impact the package name
* Update documentation at readme
* Remove codes from the extension repository

## Databases

- [x] jnosql-arangodb-extension
- [x] jnosql-cassandra-extension
- [x] jnosql-couchbase-extension
- [x] jnosql-elasticsearch-extension
- [x] jnosql-hazelcast-extension
- [x] jnosql-mongodb-extension
- [x] jnosql-orientdb-extension
- [x] jnosql-solr-extension

**Comment by otaviojava** [comment]
I've created this issue to rename the project:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2894

**Comment by otaviojava** [comment]
@dearrudam let me know if you wanna take some of this.

**Comment by dearrudam** [comment]
@otaviojava, I could work at this one:   [https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2894](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2894), but I think that I need to have permission to do it. Could you help me with that?!

**Comment by dearrudam** [comment]
@otaviojava never mind! This renaming process could be done later... 

I could work on the `jnosql-arangodb-extension`, okay? 

I got an idea: I think that you could convert each item of this "Databases" list into sub-issues. With that, any of us could assign ourselves to one of these sub-issues. Also, on each state changing of each sub-issue will be propagated to this issue automatically.

**Comment by otaviojava** [comment]
I like it; I'll take the Cassandra one to feel the terrain.

**Comment by otaviojava** [comment]
the ulrs have been updated:

* https://github.com/eclipse/jnosql-databases
* https://github.com/eclipse/jnosql-extensions

**Comment by otaviojava** [comment]
I'll close this one.
Thank you @dearrudam
