### ISSUE TITLE
Update the documentation with the new repositories URLs

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#359]
Recently, we renamed two repositories:

*  https://github.com/eclipse/jnosql-communication-driver to https://github.com/eclipse/jnosql-databases
* https://github.com/eclipse/jnosql-mapping-extension
to https://github.com/eclipse/jnosql-extensions

## Tasks

- [ ] Check the README, CONTRIBUTING, pom.xml files and validate to the new URLs

Projects to scan:

* https://github.com/eclipse/jnosql
* https://github.com/eclipse/jnosql-databases
* https://github.com/eclipse/jnosql-extensions

**Comment by Soumya-Kushwaha** [comment]
I'd like to work on this.

**Comment by otaviojava** [comment]
Hey @Soumya-Kushwaha go a head.
If you have any issues, please, let me know.

**Comment by vishalsingh2972** [comment]
@otaviojava  could you assign this to me if it is still open?
