### ISSUE TITLE
Update Eclipse JNoSQL SE samples

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#365]
### Which JNoSQL project the issue refers to?

JNoSQL Databases

### Use case

With the recent changes, we need to update the https://github.com/JNOSQL/demos-se and https://github.com/JNOSQL/demo-ee projects to use the new database structure.

### Feature proposal

The goal is to update the dependencies using the snapshot version and test those.

## Status

The checked modules below are updated already:

- [x] arangodb  - https://github.com/JNOSQL/demos-se/pull/29
- [x] arangodb-graph - https://github.com/JNOSQL/demos-se/pull/44
- [x] bean-validation - https://github.com/JNOSQL/demos-se/pull/39
- [x] cassandra - https://github.com/JNOSQL/demos-se/pull/30 
- [x] couchbase - https://github.com/JNOSQL/demos-se/pull/37
- [x] couchdb - https://github.com/JNOSQL/demos-se/pull/36
- [x] elasticsearch - https://github.com/JNOSQL/demos-se/pull/40
- [x] hazelcast - https://github.com/JNOSQL/demos-se/pull/42
- [x] janus-graph - https://github.com/JNOSQL/demos-se/pull/43
- [x] Memcached - https://github.com/JNOSQL/demos-se/pull/43
- [x] mongodb - https://github.com/JNOSQL/demos-se/pull/31 
- [x] mongodb-double - https://github.com/JNOSQL/demos-se/pull/34
- [x] neo4j - https://github.com/JNOSQL/demos-se/pull/41
- [x] redis - https://github.com/JNOSQL/demos-se/pull/32
- [x] scylla - https://github.com/JNOSQL/demos-se/pull/38

**Comment by dearrudam** [comment]
@otaviojava, the database artifacts, from `org.eclipse.jnosql.databases` groupId, are not in the Maven Central. Could you release them there in order to let us able to upgrade the sample projects, please? I mean, it'll cause problems during the CI processes when we apply these changes, am I right?

**Comment by otaviojava** [comment]
@dearrudam there are there, but as a snapshot version:

https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/jnosql/databases/

You can move those to the snapshot version without issue because the sample already has this repository on the pom.xml file:

https://github.com/JNOSQL/demos-se/blob/main/pom.xml#L133L142

**Comment by otaviojava** [comment]
Hey @dearrudam how is the issue going?

In the next call, we need to discuss this point.

It would be amazing to migrate it and then release the new version: 1.0.0


I would love to release it on June.

**Comment by dearrudam** [comment]
Hey @otaviojava, the checked modules below are updated already:

- [x] arangodb  - https://github.com/JNOSQL/demos-se/pull/29
- [ ] arangodb-graph
- [ ] bean-validation
- [x] cassandra - https://github.com/JNOSQL/demos-se/pull/30 
- [x] couchbase - https://github.com/JNOSQL/demos-se/pull/37
- [x] couchdb - https://github.com/JNOSQL/demos-se/pull/36
- [ ] document-double
- [ ] elasticsearch
- [ ] graph-janus
- [ ] graph-neo4j-remote
- [ ] hazelcast
- [ ] janus-graph
- [ ] memcached
- [x] mongodb - https://github.com/JNOSQL/demos-se/pull/31 
- [x] mongodb-double - https://github.com/JNOSQL/demos-se/pull/34
- [ ] neo4j
- [ ] record
- [x] redis - https://github.com/JNOSQL/demos-se/pull/32
- [ ] scylla

I'm working on this issue during the `Coffee.withJava` live sessions at SouJava YT channel, but I'm going to focus on this issue to make sure to make it done before the next call.

**Comment by obrunojava** [comment]
> Hey @otaviojava, the checked modules below are updated already:
> 
>     * [x]  arangodb  - [Update arangodb module to use JNoSQL Database arangodb extension JNOSQL/demos-se#29](https://github.com/JNOSQL/demos-se/pull/29)
> 
>     * [ ]  arangodb-graph
> 
>     * [ ]  bean-validation
> 
>     * [x]  cassandra - [Update cassandra module to use JNoSQL Database Cassandra Extension  JNOSQL/demos-se#30](https://github.com/JNOSQL/demos-se/pull/30)
> 
>     * [x]  couchbase - [Update `couchbase` module to use JNosql Database Couchbase Implementation JNOSQL/demos-se#37](https://github.com/JNOSQL/demos-se/pull/37)
> 
>     * [x]  couchdb - [Update `couchdb` module to use the JNoSQL Database Couchdb Implementation JNOSQL/demos-se#36](https://github.com/JNOSQL/demos-se/pull/36)
> 
>     * [ ]  document-double
> 
>     * [ ]  elasticsearch
> 
>     * [ ]  graph-janus
> 
>     * [ ]  graph-neo4j-remote
> 
>     * [ ]  hazelcast
> 
>     * [ ]  janus-graph
> 
>     * [ ]  memcached
> 
>     * [x]  mongodb - [Update mongodb module to use JNoSQL Database MongoDB Implementation JNOSQL/demos-se#31](https://github.com/JNOSQL/demos-se/pull/31)
> 
>     * [x]  mongodb-double - [Update `mongodb-double` module to use JNosql Database MongoDB Implementation JNOSQL/demos-se#34](https://github.com/JNOSQL/demos-se/pull/34)
> 
>     * [ ]  neo4j
> 
>     * [ ]  record
> 
>     * [x]  redis - [Update redis module to use JNosql Database Redis Implementation JNOSQL/demos-se#32](https://github.com/JNOSQL/demos-se/pull/32)
> 
>     * [ ]  scylla
> 
> 
> I'm working on this issue during the `Coffee.withJava` live sessions at SouJava YT channel, but I'm going to focus on this issue to make sure to make it done before the next call.

Do we have scylla support?

**Comment by otaviojava** [comment]
@obrunojava we have support using the Cassandra API.

**Comment by obrunojava** [comment]
I was talking to @dearrudam on twitter last week about implementing this example, I would like to help. Can we talk today or tomorrow on discord @dearrudam? After 5 pm I am free to talk.

**Comment by dearrudam** [comment]
Sure, @obrunojava!!! Let's talk after 5 PM BRT on [SouJava Discord Server](https://discord.gg/eAARnH7yrG)!!!

**Comment by obrunojava** [comment]
> 

As we talked yesterday @dearrudam I've got the Scylla issue to start working, ok?

**Comment by dearrudam** [comment]
FYI: 

Modules list updated! Thanks @!

The checked modules below are updated already:

- [x] arangodb  - https://github.com/JNOSQL/demos-se/pull/29
- [ ] arangodb-graph
- [ ] bean-validation
- [x] cassandra - https://github.com/JNOSQL/demos-se/pull/30 
- [x] couchbase - https://github.com/JNOSQL/demos-se/pull/37
- [x] couchdb - https://github.com/JNOSQL/demos-se/pull/36
- [ ] document-double
- [ ] elasticsearch
- [ ] graph-janus
- [ ] graph-neo4j-remote
- [ ] hazelcast
- [ ] janus-graph
- [ ] memcached
- [x] mongodb - https://github.com/JNOSQL/demos-se/pull/31 
- [x] mongodb-double - https://github.com/JNOSQL/demos-se/pull/34
- [ ] neo4j
- [ ] record
- [x] redis - https://github.com/JNOSQL/demos-se/pull/32
- [x] scylla - https://github.com/JNOSQL/demos-se/pull/38

**Comment by otaviojava** [comment]
@dearrudam I've updated the header, so you can edit the status.

**Comment by obrunojava** [comment]
The demo-ee repository is already updated? If not, I could update it next. Also, what about this `record` issue? Is to update the java classes to use a Record class?

**Comment by otaviojava** [comment]
@obrunojava, we need to update there as well.

**Comment by obrunojava** [comment]
> @obrunojava, we need to update there as well.

Thank you, I will start to work on that repository, is that ok? 

If you @dearrudam or gabriel are working there let me know, please.

**Comment by obrunojava** [comment]
> > @obrunojava, we need to update there as well.
> 
> Thank you, I will start to work on that repository, is that ok?
> 
> If you @dearrudam or gabriel are working there let me know, please.

I believe the demo-ee is already up to date, at least the version in the project pom already references the 1.0-snapshot, and we are using the jnosql.version as dependecy, I am missing something or its indeed updated?

**Comment by dearrudam** [comment]
@obrunojava yes, the [`demo-ee`](https://github.com/JNOSQL/demo-ee) repo is updated already! The [`demos-se`](https://github.com/JNOSQL/demos-se) repo is the only one that remains modules to be fixed.

**Comment by dearrudam** [comment]
@otaviojava, FIY I removed the `record` module from the task list because such one no longer exists in the repository.

**Comment by dearrudam** [comment]
@otaviojava, FIY I removed the `document-double` module from the task list because such one no longer exists in the repository.

**Comment by obrunojava** [comment]
Besides memcached I also upgrade the version of  janus-graph @dearrudam

**Comment by dearrudam** [comment]
@otaviojava, FIY I removed the `graph-janus` and `graph-neo4j-remote` modules from the task list because they no longer exist in the repository.

Mission accomplished!!! We've updated all sample codes!!! Congrats to you all !!! :clap: :clap: :clap: 

@otaviojava, I think that we're ready to release the new version: 1.0.0

**Comment by otaviojava** [comment]
Thank you, everyone!
I'll start the process to a release version today.
