### ISSUE TITLE
 Vote on Centralizing README Information for Project Demos

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#367]
### Which JNoSQL project the issue refers to?

JNoSQL Demos projects:

* https://github.com/JNOSQL/demos-se
* https://github.com/JNOSQL/demo-ee

### Use case

There is currently a discussion around centralizing the documentation for project demos. The question is whether we should keep each demo's readme information in their respective modules or consolidate it into the project's root.

While the demos currently have a readme for each one, we have received positive feedback for centralizing documentation for the [database](https://github.com/eclipse/jnosql-databases) and [extension](https://github.com/eclipse/jnosql-extensions) projects. The advantage of concentrating the demo documentation would be that it would be easily accessible to everyone at the entrance of the git repository. However, this would also mean the number of lines in the readme would increase.

We want to hold a vote to decide whether we should centralize the documentation for project demos. Please leave your vote below and let me know any other comments or concerns you may have.

## Options:

1. Could you centralize the documentation for project demos into the root of the project?
2. Could you keep the documentation for each demo in their respective modules?

Please vote by replying with either "Option 1" or "Option 2". The vote will be open for one week from the date of this post.

**Comment by dearrudam** [comment]
**Option 1**

IHMO, other problems rises when we need to keep more the one file: one is synchronization, and another is: "If something needs to be remembered manually then it'll be forgotten probably!", I mean, for files that hold codes like Java, maybe compilers can help us with that issue (okay, compilers may help us a little bit with that issue, but we know that there are corner scenarios that it doesn't)

Well, the fact is that documentation doesn't interfere with the implementation code... with that, for me, a big document file is not a problem at all!

**Comment by dearrudam** [comment]
@otaviojava what do you think to use the GitHub **Discussion** feature for voting issues like that? Here's the doc about it: https://docs.github.com/en/discussions and here's an example to you see how it works: https://github.com/dearrudam/studing-gh-issue-forms/discussions ... it's an idea only :wink:

**Comment by otaviojava** [comment]
Yeap, we can do it

**Comment by Gabrielsilvaa** [comment]
Option 1, I think this is easier to find information

**Comment by otaviojava** [comment]
Done with the first option, I merged; the issue is how to take the pictures pretty on the README.
I have now idea to fix it :)

**Comment by otaviojava** [comment]
Please, take a look and give feedback on it; for sure, we can revert this change as well.

**Comment by dearrudam** [comment]
@otaviojava LGTM :+1:
