### ISSUE TITLE
[BUG] Strange behavior in the id field name resolution on Couchdb query execution

### ISSUE THREAD

**Issue by dearrudam** [eclipse/jnosql#379]
### Which JNoSQL project the issue refers to?

JNoSQL Databases

### Bug description

During my work on PR: https://github.com/JNOSQL/demos-se/pull/36, I've tried to execute the [`App4`](https://github.com/JNOSQL/demos-se/blob/bc8e7bcd24ddf906a1c6b3c5d8ecbedcb18fedb8/couchdb/src/main/java/org/jnosql/demo/se/App4.java) class and some questions come to my mind, so, please, follow my thought:

According to the [`App4`](https://github.com/JNOSQL/demos-se/blob/bc8e7bcd24ddf906a1c6b3c5d8ecbedcb18fedb8/couchdb/src/main/java/org/jnosql/demo/se/App4.java) class, it is expected that such one will store an [`UserScopePropertiesBroken`](https://github.com/JNOSQL/demos-se/blob/bc8e7bcd24ddf906a1c6b3c5d8ecbedcb18fedb8/couchdb/src/main/java/org/jnosql/demo/se/UserScopePropertiesBroken.java#L25) instance into the database and retrieve the stored one by using the fluent query interface where the `"id"` field is equal to `"user"` and the `"scope"` is equal to `"scope"`. It was expected to retrieve the persisted previously entity but an `Optional.empty` returns instead.

I believe this behavior is expected because the `"id"` string is not the name of the [`UserScopePropertiesBroken`](https://github.com/JNOSQL/demos-se/blob/bc8e7bcd24ddf906a1c6b3c5d8ecbedcb18fedb8/couchdb/src/main/java/org/jnosql/demo/se/UserScopePropertiesBroken.java#L25) attribute mapped with `@Id` annotation: the `userName` attribute. 

I've replaced the `where` method argument with `"userName"` and then I could retrieve the persisted entity previously. Everything is okay until now. Then I tried to use `"_id"` instead of the `"userName"` string and I could retrieve the persisted entity also.

It looks like we could perform a query using `"userName"` or `"_id"` to reference the id of the entity.

**Is this behavior expected?**

**Shouldn't this query fail because the annotated field with `@Id` has a different name?** 

### JNoSQL Version

1.0.0-SNAPSHOT

### Steps To Reproduce

1. Start a CouchDB conteiner by running the following docker command:
```bash
docker run -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -d couchdb  
```
2. Perform the [`App4`](https://github.com/JNOSQL/demos-se/blob/bc8e7bcd24ddf906a1c6b3c5d8ecbedcb18fedb8/couchdb/src/main/java/org/jnosql/demo/se/App4.java#L39) changing the `where` method argument with `"id"` string: an Optional.empty should returns;

3. Delete the persisted data or re-create the CouchDB container by executing step 1.

4. Perform the [`App4`](https://github.com/JNOSQL/demos-se/blob/bc8e7bcd24ddf906a1c6b3c5d8ecbedcb18fedb8/couchdb/src/main/java/org/jnosql/demo/se/App4.java#L39) changing the `where` method argument with `"userName"` string: the persisted data should returns; 

5. Delete the persisted data or re-create the CouchDB container by executing step 1.

6. Perform the [`App4`](https://github.com/JNOSQL/demos-se/blob/bc8e7bcd24ddf906a1c6b3c5d8ecbedcb18fedb8/couchdb/src/main/java/org/jnosql/demo/se/App4.java#L39) changing the `where` method argument with `"_id"` string: the persisted data should returns;  

### Expected Results

Only the query execution with the `where` method with "userName" as argument should retrieve the expected persisted data.

### Code example, screenshot, or link to a repository

![image](https://github.com/eclipse/jnosql/assets/6537623/d8c5e97a-64b3-4dc3-a401-879d8fc0dc63)

![image](https://github.com/eclipse/jnosql/assets/6537623/3ac193b0-2773-4a27-80b0-201176a663e5)

**Comment by otaviojava** [comment]
Hey Max, if we look at the `Id` annotation, it provides the`_id` as default:

```java
String value() default "_id";
```

Thus, the native name is `id` on the database.

What Eclipse JNoSQL do in both case is convert the "field" to the native name, or if it does not find it will keep so:

* When we query by "name" -> it will convert to native, then the "_id".
* When we query by "_id" -> it won't find this mapper information, so it will keep as there is: "_id".

**Comment by dearrudam** [comment]
Hey Otavio, thanks for the answer!

I didn't take a look at the mapping resolution implementation. Next time I'll take a look on it more deeply in order to understand more the whole process execution.

Again, thanks!

I'm going to close this issue.

**Comment by otaviojava** [comment]
@dearrudam there is no issue with asking Max.

Feel free to ask as much as you can/wish.

That is our pleasure to help.
