### ISSUE TITLE
Increase the Support for DynamoDB

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#380]
### Database name

DynamoDB

### Database details

We currently have DynamoDB in our repository but with a massive leak of documentation and test.

We need to check if we want to keep this database, and if yes, we need to:

- [x] Create documentation on `README` fixed: https://github.com/eclipse/jnosql-databases/pull/219
- [x] Create TestContainer test for it. Fixed: https://github.com/eclipse/jnosql-databases/pull/219
- [x] Provide support to Document API. Fixed: https://github.com/eclipse/jnosql-databases/pull/260

### Relevance

It is relevant because we already have it in our repository.

**Comment by dearrudam** [comment]
@otaviojava, the AWS DynamoDB API is providing an interesting way to supporting to persist and query data in its key-value data structure, maybe we could provide support for the **Document** NoSQL API. What do you think?

**Comment by otaviojava** [comment]
@dearrudam if they can support both, go for it :)

**Comment by otaviojava** [comment]
@dearrudam I've updated to on more item. That is the document support.

**Comment by bbwithpointers** [comment]
Hello guys, how you doing? How can I help with this task? Is this what you and Gabriel are working on the SouJava lives right now @dearrudam ?

**Comment by dearrudam** [comment]
Hey @bbwithpointers, how are you doing?
Yeah! Gabriel and I are doing the "Coffee.withJava" series on the SouJava Youtube channel by talking about contributing to this project, but in the last lives we have been working on this issue: #365

**Comment by dearrudam** [comment]
@bbwithpointers, it'll be awesome to work on this task together! Let's book a discussion! What do you think?!

**Comment by bbwithpointers** [comment]
@dearrudam lets do it, would be a honor :)

**Comment by techpordentro** [comment]
Hello guys, how you doing? Is the last issue still open? Can I help you @dearrudam if so?

**Comment by dearrudam** [comment]
Sure! Let's book a meeting to talk about it!

**Comment by dearrudam** [comment]
@otaviojava, FYI I'm working on it! Here's the branch with such codes: https://github.com/dearrudam/jnosql-databases/tree/feat/dynamodb-document-support

**Comment by otaviojava** [comment]
That is nice @dearrudam 
You can create draft if you wish, so everyone can check the status in live.

**Comment by dearrudam** [comment]
That's great!!! It's my first draft PR!!! https://github.com/eclipse/jnosql-databases/pull/260

Thanks, @otaviojava

**Comment by dearrudam** [comment]
I'll close it because the bullet points were completed
