### ISSUE TITLE
Create integration tests on the repositories databases

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#382]
### Which JNoSQL project the issue refers to?

JNoSQL Databases

### Use case

After fixing the issue with a single repository by database, it allows us to move as next move on quality to create more integration tests on each NoSQL database module.

Currently, we have two test domains:
mapping: focusing on the Java integration until the communication layer
communication: the communication until the database.

The goal is to have a third domain to test as one with the "integration" domain. 

As the pyramid test, we can cover only, initially, cover the CRUD operations mainly because it is a more expensive test. 

:warning: This new test does not remove the need for the other tests.

To avoid any new issues on injection, we should also move the injection by constructor instead of a field, once; we can do it on the latest version:

https://github.com/jakartaee/cdi/issues/464

### Databases

- [x] MongoDB https://github.com/eclipse/jnosql-databases/pull/222
- [x] ArangoDB https://github.com/eclipse/jnosql-databases/pull/223
- [x] Cassandra https://github.com/eclipse/jnosql-databases/pull/223
- [x] Couchbase
- [x] Elasticsearh https://github.com/eclipse/jnosql-databases/pull/223
- [x] Hazelcast https://github.com/eclipse/jnosql-databases/pull/223
- [x] OrientedDB https://github.com/eclipse/jnosql-databases/pull/223
- [x] Solr https://github.com/eclipse/jnosql-databases/pull/223

**Comment by dearrudam** [comment]
@otaviojava, FYI, I'm working on two issues (on this one and on the #381) related to the Couchbase JNoSQL Database implementation already. I'm intent to push up these changes tomorrow, 23rd May
