### ISSUE TITLE
Allow custom/base repositories without generic type definition 

### ISSUE THREAD

**Issue by georgleber** [eclipse/jnosql#414]
**Currently a specific repository besides one of the Jakarta Data repositories (CrudRepository, PageableRepository, ...) can extend an interface where additional base queries are defined. The extended interface must have a generic type corresponding to the entity for which the repository is used.** 

As a:

- [ ] Application user/user of the configuration itself
- [x] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I want to be able to:

Define a repository without a generic type, because the type information might not be needed.

...which enables me to:

Be free in my decision as application developer if a type is needed or not. If the BaseQueries are just relevant for one entity there is no need to use a generic type, because it is only usable in the context of the entity.

**Comment by otaviojava** [comment]
Hey @georgleber , how are you?

Thank you, that is something that we can work on next release.

Thus, we will have the entire august to work on it.
