### ISSUE TITLE
[BUG] There is no way to configure ArangoSerde used by ArangoDBDocumentManager

### ISSUE THREAD

**Issue by m4ttek** [eclipse/jnosql#437]
### Which JNoSQL project the issue refers to?

JNoSQL Databases

### Bug description

`ArangoDBDocumentConfiguration` class is final what makes impossible to override protected method `getArangoDB` present in `ArangoDBConfiguration` class.

There is also no way to Inject your own `ArangoDB` object with custom configuration.

`ArangoDBDocumentManager` interface does not give possibility to get `ArangoDB` object also. And its implementation `DefaultArangoDBDocumentManager` is package private.

### JNoSQL Version

1.0.1

### Steps To Reproduce

Try to customize ArangoDB.Builder with your own configuration that requires programmatic settings and object creation.

### Expected Results

I should be able to inject or intercept or at least override `ArangoDB` object creation.

**Comment by m4ttek** [comment]
To give more context - I'd like to provide user-data serde, according to https://www.arangodb.com/docs/stable/drivers/java-reference-serialization.html#custom-serializers

**Comment by otaviojava** [comment]
@m4ttek thank you for those points; we will work to release in this next version.

**Comment by otaviojava** [comment]
I got an idea using the properties:


```properties
jnosql.arangodb.deserializer.1=the class path
jnosql.arangodb.deserializer.2=the class path
jnosql.arangodb.seserializer.1=the class path
jnosql.arangodb.seserializer.2=the class path
```

I will create the implementation and request your help for review it.

**Comment by otaviojava** [comment]
I have the draft work here:

https://github.com/eclipse/jnosql-databases/pull/242

**Comment by otaviojava** [comment]
Hey @m4ttek, I got a good point at the Draft.

Why @org.eclipse.jnosql.mapping.Convert won't work on your case?

You could create your converter:

```java
@Column
@Convert(MoneyConverter.class)
private Currency currency;
```


And implement this way:

```java
public class MoneyConverter implements AttributeConverter<Currency, String> {

    @Override
    public String convertToDatabaseColumn(Currency attribute) {
        return attribute.getCurrencyCode();
    }

    @Override
    public Currency convertToEntityAttribute(String dbData) {
        return Currency.getAvailableCurrencies().stream()
                .filter(c -> dbData.equals(c.getCurrencyCode()))
                .findAny().orElse(null);
    }
}
```

**Comment by m4ttek** [comment]
Ok, I get it, but still it doesn't allow me to specify how serde should work for whole entity (like standard Java `Externalizable` interface).

So, maybe, we should look into it from the other side and give access to creating custom `ArangoDB` instance with custom serialization objects if needed?
