### ISSUE TITLE
Add CI support for Java 21

### ISSUE THREAD

**Issue by dearrudam** [eclipse/jnosql#440]
Last September 19th, the latest Java LTS, Java 21 was released and we should be able to run the source code against Java 21.

This issue will create a GitHub Action, CI, to run the source code against Java 21; this won't impact the code behavior.
It is an excellent issue to the first contribution.

To-Do:

- [ ] Create a GitHub Action that runs the Jakarta NoSQL source code against Java 21
- [ ] Test the Action and ensure it correctly detects any compatibility issues
- [ ] Update the README to document the new CI support for Java 21

**Comment by otaviojava** [comment]
That is nice!!!
Thank you Max.
