### ISSUE TITLE
[BUG] query specification doesnt allow for dashes in tablenames

### ISSUE THREAD

**Issue by warmuuh** [eclipse/jnosql#441]
### Which JNoSQL project the issue refers to?

JNoSQL (Core)

### Bug description

the antlr4 spec ([code](https://github.com/eclipse/jnosql/blob/main/antlr4/org/eclipse/jnosql/query/grammar/Query.g4#L58)) doesnt allow for table-names with dashes, so this query is invalid and cannot be parsed:
```
select * from my-prefix-user where user_id = 123
```

especially for dynamodb tables, dashes are pretty common

### JNoSQL Version

1.0.1

### Steps To Reproduce

see above

### Expected Results

this query can be parsed:

```
select * from my-prefix-user where user_id = 123
```

### Code example, screenshot, or link to a repository

```
select * from my-prefix-user where user_id = 123
```

**Comment by otaviojava** [comment]
Thank you, we will fix it.

**Comment by otaviojava** [comment]
@warmuuh we will release the release at the end of this month.
