### ISSUE TITLE
Add CI into the JNoSQL Extensions project to support for Java 21

### ISSUE THREAD

**Issue by dearrudam** [eclipse/jnosql#443]
Last September 19th, the latest Java LTS, Java 21 was released and [JNoSQL Extensions project](https://github.com/eclipse/jnosql-extensions) should be able to run against Java 21.

This issue will create a GitHub Action, CI, to run the source code against Java 21; this won't impact the code behavior.
It is an excellent issue to the first contribution.

To-Do:

- [x] Create a GitHub Action that runs the Jakarta NoSQL source code against Java 21
- [x] Test the Action and ensure it correctly detects any compatibility issues
- [x] Update the README to document the new CI support for Java 21

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by dearrudam** [comment]
Yes, @vimalJD! The [JNoSQL Extensions project](https://github.com/eclipse/jnosql-extensions) is active!

The Eclipse JNoSQL Mapping Extension API is a collection of implementations/specializations from the [Jakarta NoSQL](https://jakarta.ee/specifications/nosql/) specification that defines specific behavior in various NoSQL databases.

To learn more about how to contribute to this project, take a look at the [Contributing section](https://github.com/eclipse/jnosql-extensions#contributing) in the [README](https://github.com/eclipse/jnosql-extensions/blob/main/README.adoc) file, please. 👍
