### ISSUE TITLE
[BUG] deleteAll does not delete anything in Arango Repository

### ISSUE THREAD

**Issue by m4ttek** [eclipse/jnosql#451]
### Which JNoSQL project the issue refers to?

JNoSQL (Core)

### Bug description

When deleteAll method is invoked on Arango Repoistory it does not delete anything as the following check blocks it:

![image](https://github.com/eclipse/jnosql/assets/6191860/53899e00-7b89-4df2-88c8-5a2fcd33fc54)

### JNoSQL Version

JNoSQL version

### Steps To Reproduce

Invoke deleteAll method on any collection consisting some records.

### Expected Results

All records should be deleted (consider using truncate method from arango driver?)

**Comment by otaviojava** [comment]
Hey @m4ttek thank you for reporting a bug, we are working to fix it ASAP.
