### ISSUE TITLE
[BUG] ArangoRepository save method interally uses updateDocument instead of replaceDocument

### ISSUE THREAD

**Issue by m4ttek** [eclipse/jnosql#455]
### Which JNoSQL project the issue refers to?

JNoSQL Databases

### Bug description

Once a document is saved in collection, there is no possiblity to nullify any given field, as it uses updateDocument method internally, instead of replaceDocument.

Unfortunately, I have to delete such record first, to update it, which is not a satisfactory solution ;)

And, I believe there should be dirty checking of values in any entity, but replaceDocument will also work.

### JNoSQL Version

1.0.2

### Steps To Reproduce

1. Save any given document with example values
2. Try to update it with some nullified fields.

### Expected Results

Save method should use replaceDocumento, not updateDocument from arango driver

**Comment by otaviojava** [comment]
@m4ttek hey, thank you for the report. We are working on it.

**Comment by otaviojava** [comment]
We've released a new version with this fix.
