### ISSUE TITLE
[REDIS] include support for Sentinel configuration. 

### ISSUE THREAD

**Issue by marcelolemes** [eclipse/jnosql#534]
### Database name

redis

### Database version

non applicable

### Any operation fails?

Not.

### Any operation is missing?

...I need to be able to:

Have the possibility of using functionality (sentinel-client) to consume a Redis high availability arrangement

Source: https://redis.io/docs/latest/operate/oss_and_stack/management/sentinel/

Redirection of this [issue](https://github.com/jakartaee/nosql/issues/177)

**Comment by dearrudam** [comment]
Fixed with https://github.com/eclipse/jnosql-databases/pull/297
