### ISSUE TITLE
[BUG] JDQL queries with like operator not working

### ISSUE THREAD

**Issue by m4ttek** [eclipse/jnosql#540]
### Which JNoSQL project the issue refers to?

JNoSQL (Core)

### Bug description

 There is no way I can use `@Query` annotation properly with LIKE queries with params.

For example:
```
    @Query("where employeeName LIKE ?1 OR employeeSurname LIKE ?1")
    Page<EmployeeWorkflowContext> searchByPhrase(@Param("phrase") String phrase,
                                                 @NotNull PageRequest pageRequest,
                                                 @NotNull Order<EmployeeWorkflowContext> order);
```

It results in error while invoking:
```
WARNING: An exception mapping did not successfully produce and processed a response. Logging the exception propagated to the default exception mapper.
org.eclipse.jnosql.communication.QueryException: line 1:24 mismatched input '?' expecting STRING
```

It doesn't matter if I use named parameter or not - it's expecting string after "like":

### JNoSQL Version

1.1.1

### Steps To Reproduce

1. Create a Repository with custom @Query method
2. Use "LIKE" operator for this method with interpolated parameter.
3. Invoke this method

**Comment by otaviojava** [comment]
Hey @m4ttek could you check it with SNAPSHOT?

**Comment by m4ttek** [comment]
Unfortunately, still not working on 1.1.2-SNAPSHOT
![image](https://github.com/user-attachments/assets/d109eb52-7ab7-4502-bd32-cf529689e1e0)

**Comment by otaviojava** [comment]
I got it; it generates once a day.
I am generating it for you.

**Comment by m4ttek** [comment]
Yes, and now it's working!

**Comment by otaviojava** [comment]
Thank you @m4ttek closing thi sissue.
