### ISSUE TITLE
[BUG] Using skip with DocumentTemplate does not have any effect

### ISSUE THREAD

**Issue by m4ttek** [eclipse/jnosql#550]
### Which JNoSQL project the issue refers to?

JNoSQL (Core)

### Bug description

There is no possiblity to paginate records using `SelectQueryBuilder` and `DocumentTemplate`, specifically `ArangoDBTemplate`. `PageRequest` is also being ignored in queries.

Skip parameter is ignored and so I cannot paginate results with it.

### JNoSQL Version

1.1.1

### Steps To Reproduce

Build an example SelectQuery with `skip` and `limit` parameters set and try to invoke it on a `DocumentTemplate` object.

### Expected Results

Records returned by select query should be properly paginated.

### Code example, screenshot, or link to a repository

```
        return arangoDBTemplate.selectCursor(buildSelectQuery(filterCriteria)
                .sort(order.sorts().toArray(Sort[]::new))
                .skip((pageRequest.page() - 1) * pageRequest.size()) // it doesn't work
                .limit(pageRequest.size())
                .build(), pageRequest);
```

**Comment by otaviojava** [comment]
Thanks @m4ttek 
I am working on it.

**Comment by otaviojava** [comment]
Hey @m4ttek 
I've created the DRAFT PR, but I could not generate the issue:

https://github.com/eclipse/jnosql-databases/pull/283

**Comment by m4ttek** [comment]
@otaviojava it is the last method in `SemiStructuredTemplate` interface - it takes a `PageRequest` object as second parameter. Hence it shouldn't be necessary to invoke skip or limit - but it doesn't work neither.

**Comment by otaviojava** [comment]
@m4ttek, it is a documentation issue.

I've created the offset for this type of query; however, it will overwrite the `SelectQuery` in both cases based on the PageRequest.

If you don't want you can use the `  <T> Stream<T> select(SelectQuery query);`

Once again, thank you for finding the bug.

**Comment by m4ttek** [comment]
@otaviojava great, thanks for info. If you release a new version, I'll check it :)

**Comment by otaviojava** [comment]
@m4ttek deploy as SNAPSHOT, could you try it?

We are working on finishing the TCK of Jakarta Data; as soon we finish, we will release a new version.

**Comment by m4ttek** [comment]
@otaviojava it seems to be working now :)

**Comment by otaviojava** [comment]
@m4ttek thanks for the feedback
