### ISSUE TITLE
[BUG] Ensure Eclipse JNoSQL Compatibility with Jakarta Data - 5 Failed Tests

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#552]
### Which JNoSQL project the issue refers to?

JNoSQL (Core)

### Bug description

As part of our efforts to ensure compatibility with Jakarta Data, we have identified six tests currently failing in Eclipse JNoSQL. Addressing these issues is crucial to meet the Jakarta Data specifications. Below is a summary of the failing tests and the issues associated with each:

- [x] 1. **testCursoredPageOf7FromCursor**:

   - The test is failing and needs investigation to ensure proper cursored pagination is implemented.

- [x] 2. **testQueryWithOr**:
   - **Discussion Required**: This test's rule is valid for SQL databases but may not be applicable for NoSQL databases. We need to discuss and determine the correct behavior for NoSQL and adjust the test accordingly.

- [x] 3. **testQueryWithNot**:
   - The failure appears to be related to the MongoDB driver. The issue stems from the need to aggregate the negation using the `$nor` operator. We need to adjust the implementation to accommodate this.

- [x] 4. **testFirstCursoredPageOf8AndNextPages**:
   - Similar to the first test, this one also involves cursored pagination but fails when transitioning between pages. This needs to be fixed to ensure smooth pagination.

- [x] 5. **testUpdateQueryWithWhereClause**:
   - There is an issue related to UUID handling in MongoDB. We need to include UUID as a reader to ensure correct query behavior in MongoDB.

- [x] 6. **findByNumTypeAndNumBitsRequiredLessThan**:
   - This failure is due to a difference in how enums are serialized. In relational databases, enums are serialized using their ordinal, while NoSQL databases use the name. We must align the serialization method across databases or appropriately handle this difference.

### Proposed Fixes:

1. Investigate and fix pagination issues in `testCursoredPageOf7FromCursor` and `testFirstCursoredPageOf8AndNextPages`.
2. Discuss and determine the correct behavior for `testQueryWithOr` in a NoSQL context.
3. Modify the MongoDB implementation to use `$nor` for negation in `testQueryWithNot`.
4. Add UUID as a reader in MongoDB to fix `testUpdateQueryWithWhereClause`.
5. Address enum serialization differences in `findByNumTypeAndNumBitsRequiredLessThan`.

### JNoSQL Version

JNoSQL version

### Steps To Reproduce

Run Jakarta Data NoSQL.

### Expected Results

Pass the TCK.

**Comment by otaviojava** [comment]
I am working on: **testUpdateQueryWithWhereClause**

**Comment by dearrudam** [comment]
I am working on: **testQueryWithNot**

**Comment by otaviojava** [comment]
I am working on: testFirstCursoredPageOf8AndNextPages

**Comment by otaviojava** [comment]
@dearrudam I've passed all the tests.

**Comment by otaviojava** [comment]
All of those 74 tests have been passed!

![Screenshot 2024-09-13 at 07 19 27](https://github.com/user-attachments/assets/0806b008-971f-47d2-a9d0-5fc7f8bda471)
ed.

**Comment by dearrudam** [comment]
Wow!!! That's amazing!!! Congrats!!!

**Comment by otaviojava** [comment]
This weekend, I will work on a new release version. 

It has been a couple month without a new version release.
