### ISSUE TITLE
[BUG] MongoDB conversions applied also to other databases

### ISSUE THREAD

**Issue by rashtao** [eclipse/jnosql#565]
### Which JNoSQL project the issue refers to?

JNoSQL Databases

### Bug description

MongoDB implementation provides the following ValueWriter and ValueReader(s):
- `org.eclipse.jnosql.databases.mongodb.communication.UUIDValueWriter`
- `org.eclipse.jnosql.databases.mongodb.communication.BinaryValueReader`
- `org.eclipse.jnosql.databases.mongodb.communication.UUIDValueReader`

Unfortunately, ValueWriters and ValueReaders are not restricted to a specific database, but are used in the mapping conversions of any other database in the application, as long as `jnosql-mongodb` is in the classpath.

### JNoSQL Version

1.1.4-SNAPSHOT

### Steps To Reproduce

1. Create an application using `jnosql-mongodb` and `jnosql-arangodb`.
2. Create an entity class having a `UUID` field
3. Save an entity instance to ArangoDB
4. Read the saved entity from ArangoDB

(3.) will use `org.eclipse.jnosql.databases.mongodb.communication.UUIDValueWriter`

(4.) will use `org.eclipse.jnosql.databases.mongodb.communication.UUIDValueReader`

**Comment by otaviojava** [comment]
Thank you, @rashtao. Great feedback.

I've fixed it.

Feel free to open it in case it did not fix it.
